### ISSUE TITLE
How to use the epos reader properly?

### ISSUE THREAD

**Issue by skatnagallu** [atomprobe-tc/ifes_apt_tc_data_modeling#4]
I am trying to use the epos reader.
when I create an epos object using the reader class, I correctly get the number of events 
```
>>> epos.number_of_events
6596033
```
However, when I am trying to get values in the file, I get this error for all the available methods.
```
>>> m = epos.get_mass_to_charge_state_ratio()
>>> m.values
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NxField' object has no attribute 'values'
```
Am I doing something wrong? Any help would be greatly appreciated.

**Comment by mkuehbach** [comment]
Dear @skatnagallu:
 
Which version of the ifes_apt_tc_data_modeling library are you using? I suppose you use some.
I have done heavy refactoring of this library last month and just today merged and pushed that new version on pypi.
Today is my first day after the parental leave vacation.
Using >=v0.2 reading should work like this: See an example here how it is done in paraprobe:
https://gitlab.com/paraprobe/paraprobe-toolbox/-/blob/main/code/transcoder/src/python/paraprobe_transcoder.py?ref_type=heads line 134 and following.

If the issue persist, let's meet for a short zoom to get it working for you and if necessary I can then fix it immediately.
As you will be likely using the multiplicities and so on it would be good if you also have a critical look into this function
https://github.com/atomprobe-tc/ifes_apt_tc_data_modeling/blob/main/ifes_apt_tc_data_modeling/epos/epos_reader.py
and confirm or suggest changes where the description is incorrect.

Thank you very much, Markus

**Comment by skatnagallu** [comment]
Indeed I was using the older version. I will use the new version and keep you posted.
